# Generated by Django 5.1.6 on 2026-06-12 14:56

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['category_name'],
            },
        ),
        migrations.CreateModel(
            name='AstrologyKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('nakshatra', 'Nakshatra'), ('nakshatra_pada', 'Nakshatra Pada'), ('dosha', 'Dosha'), ('planet_in_house', 'Planet in House'), ('planet_in_nakshatra', 'Planet in Nakshatra'), ('planet_in_sign', 'Planet in Sign'), ('arudha_lagna', 'Arudha Lagna'), ('dasha', 'Dasha'), ('transit', 'Transit'), ('kp', 'KP'), ('bnn', 'BNN'), ('past_life', 'Past Life'), ('remedy', 'Remedy'), ('research', 'Research'), ('case_study', 'Case Study')], max_length=40)),
                ('knowledge_type', models.CharField(choices=[('prediction', 'Prediction'), ('remedy', 'Remedy'), ('rule', 'Rule'), ('observation', 'Observation'), ('question', 'Question'), ('note', 'Note')], max_length=30)),
                ('applies_to_type', models.CharField(choices=[('nakshatra', 'Nakshatra'), ('pada', 'Pada'), ('dosha', 'Dosha'), ('planet', 'Planet'), ('house', 'House'), ('sign', 'Sign'), ('planet_combination', 'Planet Combination'), ('arudha', 'Arudha'), ('dasha', 'Dasha'), ('transit', 'Transit'), ('general', 'General')], default='general', max_length=40)),
                ('applies_to_name', models.CharField(blank=True, max_length=150)),
                ('applies_to_subtype', models.CharField(blank=True, max_length=150)),
                ('related_factor', models.CharField(blank=True, max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('verification_question', models.TextField(blank=True)),
                ('expected_result', models.TextField(blank=True)),
                ('nature', models.CharField(choices=[('positive', 'Positive'), ('negative', 'Negative'), ('neutral', 'Neutral'), ('remedy', 'Remedy')], default='neutral', max_length=20)),
                ('confidence_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='medium', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='knowledge_updated', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='knowledge_records', to='knowledge.category')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='CustomerKnowledgeTracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_type', models.CharField(choices=[('prediction_verification', 'Prediction Verification'), ('remedy_tracking', 'Remedy Tracking'), ('research_answer', 'Research Answer'), ('observation', 'Observation')], max_length=40)),
                ('status', models.CharField(choices=[('applies', 'Applies'), ('partially_applies', 'Partially Applies'), ('does_not_apply', 'Does Not Apply'), ('not_asked', 'Not Asked'), ('suggested', 'Suggested'), ('started', 'Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('stopped', 'Stopped'), ('answered', 'Answered'), ('not_answered', 'Not Answered'), ('needs_follow_up', 'Needs Follow-up')], default='not_asked', max_length=40)),
                ('customer_feedback', models.TextField(blank=True)),
                ('researcher_notes', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('effectiveness_rating', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('outcome', models.CharField(blank=True, choices=[('very_effective', 'Very Effective'), ('effective', 'Effective'), ('partial', 'Partial'), ('no_effect', 'No Effect'), ('negative_effect', 'Negative Effect'), ('not_applicable', 'Not Applicable')], max_length=30)),
                ('verified_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='knowledge_tracking_records', to='customers.customer')),
                ('knowledge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_tracking_records', to='knowledge.astrologyknowledge')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_tracking_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
