# Generated by Django 5.1.6 on 2026-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerknowledgetracking',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
