# Generated by Django 5.1.6 on 2026-06-12 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('knowledge', '0005_distinguish_topic_category_labels'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='astrologyknowledge',
            name='life_areas',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='astrologyknowledge',
            name='short_meaning',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='astrologyknowledge',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('researching', 'Researching'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='astrologyknowledge',
            name='system',
            field=models.CharField(choices=[('classical_astrology', 'Classical Astrology'), ('bnn', 'BNN'), ('kp', 'KP'), ('numerology', 'Numerology'), ('jaimini', 'Jaimini')], default='classical_astrology', max_length=40),
        ),
        migrations.AlterField(
            model_name='astrologyknowledge',
            name='section',
            field=models.CharField(choices=[('nakshatra', 'Nakshatra'), ('nakshatra_pada', 'Nakshatra Pada'), ('dosha', 'Dosha'), ('planet_in_house', 'Planet in House'), ('planet_in_nakshatra', 'Planet in Nakshatra'), ('planet_in_sign', 'Planet in Sign'), ('arudha_lagna', 'Arudha Lagna'), ('dasha', 'Dasha'), ('transit', 'Transit'), ('kp', 'KP'), ('bnn', 'BNN'), ('past_life', 'Past Life'), ('remedy', 'Remedy'), ('research', 'Research'), ('case_study', 'Case Study'), ('yoga', 'Yoga'), ('age_activation', 'Age Activation'), ('kp_rule', 'KP Rule'), ('numerology_number', 'Numerology Number')], max_length=40),
        ),
        migrations.CreateModel(
            name='HypothesisQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('question_type', models.CharField(choices=[('yes_no', 'Yes/No'), ('rating', 'Rating'), ('text', 'Text'), ('single_choice', 'Single Choice'), ('multiple_choice', 'Multiple Choice')], default='yes_no', max_length=30)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='knowledge.astrologyknowledge')),
            ],
            options={
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerResearchAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(blank=True)),
                ('answer_value', models.CharField(blank=True, max_length=100)),
                ('notes', models.TextField(blank=True)),
                ('answered_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('answered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='research_answers_recorded', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_answers', to='customers.customer')),
                ('hypothesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='research_answers', to='knowledge.astrologyknowledge')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_answers', to='knowledge.hypothesisquestion')),
            ],
            options={
                'ordering': ['-answered_date', '-created_at'],
                'constraints': [models.UniqueConstraint(fields=('customer', 'hypothesis', 'question'), name='unique_customer_hypothesis_question_answer')],
            },
        ),
    ]
