# Generated by Django 5.1.6 on 2026-06-13 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0006_astrologyknowledge_life_areas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrologyknowledge',
            name='section',
            field=models.CharField(choices=[('nakshatra', 'Nakshatra'), ('nakshatra_pada', 'Nakshatra Pada'), ('dosha', 'Dosha'), ('planet_in_house', 'Planet in House'), ('planet_in_nakshatra', 'Planet in Nakshatra'), ('planet_in_nakshatra_pada', 'Planet in Nakshatra Pada'), ('planet_in_sign', 'Planet in Sign'), ('house_lord_in_house', 'House Lord in House'), ('arudha_lagna', 'Arudha Lagna'), ('dasha', 'Dasha'), ('transit', 'Transit'), ('kp', 'KP'), ('bnn', 'BNN'), ('bnn_rule', 'BNN Rule'), ('past_life', 'Past Life'), ('remedy', 'Remedy'), ('research', 'Research'), ('case_study', 'Case Study'), ('yoga', 'Yoga'), ('age_activation', 'Age Activation'), ('kp_rule', 'KP Rule'), ('numerology_number', 'Numerology Number')], max_length=40),
        ),
    ]
