# Generated by Django 5.1.6 on 2026-06-13 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('knowledge', '0007_alter_astrologyknowledge_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='astrologyknowledge',
            name='section',
            field=models.CharField(choices=[('lagna', 'Lagna'), ('nakshatra', 'Nakshatra'), ('nakshatra_pada', 'Nakshatra Pada'), ('dosha', 'Dosha'), ('planet_in_house', 'Planet in House'), ('planet_in_nakshatra', 'Planet in Nakshatra'), ('planet_in_nakshatra_pada', 'Planet in Nakshatra Pada'), ('planet_in_sign', 'Planet in Sign'), ('house_lord_in_house', 'House Lord in House'), ('house_lord_in_sign', 'House Lord in Sign'), ('house_lord_in_nakshatra', 'House Lord in Nakshatra'), ('house_lord_in_nakshatra_pada', 'House Lord in Nakshatra Pada'), ('conjunction', 'Conjunction'), ('aspect', 'Aspect'), ('arudha_lagna', 'Arudha Lagna'), ('dasha', 'Dasha'), ('transit', 'Transit'), ('kp', 'KP'), ('house_signification', 'House Signification'), ('planet_significator', 'Planet Significator'), ('cuspal_sub_lord', 'Cuspal Sub Lord'), ('marriage_rule', 'Marriage Rule'), ('career_rule', 'Career Rule'), ('child_birth_rule', 'Child Birth Rule'), ('property_rule', 'Property Rule'), ('foreign_travel_rule', 'Foreign Travel Rule'), ('health_rule', 'Health Rule'), ('bnn', 'BNN'), ('bnn_rule', 'BNN Rule'), ('planet_activation_age', 'Planet Activation Age'), ('planet_combination', 'Planet Combination'), ('planet_chain', 'Planet Chain'), ('signification_transfer', 'Signification Transfer'), ('house_activation', 'House Activation'), ('event_timing', 'Event Timing'), ('marriage_pattern', 'Marriage Pattern'), ('career_pattern', 'Career Pattern'), ('spiritual_pattern', 'Spiritual Pattern'), ('karmic_pattern', 'Karmic Pattern'), ('life_path_number', 'Life Path Number'), ('destiny_number', 'Destiny Number'), ('soul_urge_number', 'Soul Urge Number'), ('personality_number', 'Personality Number'), ('name_number', 'Name Number'), ('personal_year_number', 'Personal Year Number'), ('compatibility', 'Compatibility'), ('financial_pattern', 'Financial Pattern'), ('relationship_pattern', 'Relationship Pattern'), ('health_pattern', 'Health Pattern'), ('atmakaraka', 'Atmakaraka'), ('amatyakaraka', 'Amatyakaraka'), ('darakaraka', 'Darakaraka'), ('karakamsha_lagna', 'Karakamsha Lagna'), ('swamsha', 'Swamsha'), ('pada_analysis', 'Pada Analysis'), ('chara_dasha', 'Chara Dasha'), ('upapada_lagna', 'Upapada Lagna'), ('career_indicators', 'Career Indicators'), ('marriage_indicators', 'Marriage Indicators'), ('spiritual_indicators', 'Spiritual Indicators'), ('past_life', 'Past Life'), ('remedy', 'Remedy'), ('research', 'Research'), ('case_study', 'Case Study'), ('yoga', 'Yoga'), ('age_activation', 'Age Activation'), ('kp_rule', 'KP Rule'), ('numerology_number', 'Numerology Number'), ('divisional_chart', 'Divisional Chart')], max_length=40),
        ),
    ]
