# Generated by Django 5.1.6 on 2026-06-12 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_type', models.CharField(choices=[('Occupation', 'Occupation'), ('Education', 'Education'), ('Marital Status', 'Marital Status'), ('Gender', 'Gender'), ('Timezone', 'Timezone'), ('Consultation Topic', 'Consultation Topic'), ('Knowledge Type', 'Knowledge Type'), ('Section', 'Section'), ('Applies To Type', 'Applies To Type'), ('Related Factor', 'Related Factor'), ('Tracking Type', 'Tracking Type'), ('Verification Status', 'Verification Status'), ('Remedy Status', 'Remedy Status'), ('Research Status', 'Research Status'), ('Outcome', 'Outcome'), ('Role Type', 'Role Type')], max_length=100)),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='settings_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['setting_type', 'sort_order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('setting_type', 'name'), name='unique_setting_option_type_name')],
            },
        ),
    ]
