# Generated by Django 5.1.6 on 2026-06-12 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seed_setting_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_type', models.CharField(choices=[('Astrology API', 'Astrology API'), ('Email', 'Email'), ('SMS', 'SMS'), ('WhatsApp', 'WhatsApp'), ('General', 'General')], max_length=50)),
                ('config_name', models.CharField(max_length=150)),
                ('provider_name', models.CharField(blank=True, max_length=150)),
                ('api_url', models.URLField(blank=True)),
                ('api_key', models.CharField(blank=True, max_length=255)),
                ('api_secret', models.CharField(blank=True, max_length=255)),
                ('sender_email', models.EmailField(blank=True, max_length=254)),
                ('smtp_host', models.CharField(blank=True, max_length=150)),
                ('smtp_port', models.PositiveIntegerField(blank=True, null=True)),
                ('username', models.CharField(blank=True, max_length=150)),
                ('password', models.CharField(blank=True, max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_configs_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_configs_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['config_type', 'config_name'],
            },
        ),
    ]
