# Generated by Django 5.1.6 on 2026-06-12 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateTimeField()),
                ('topic', models.CharField(choices=[('career', 'Career'), ('marriage', 'Marriage'), ('health', 'Health'), ('finance', 'Finance'), ('education', 'Education'), ('spiritual_guidance', 'Spiritual Guidance'), ('general_consultation', 'General Consultation')], default='general_consultation', max_length=40)),
                ('notes', models.TextField()),
                ('follow_up_required', models.BooleanField(default=False)),
                ('follow_up_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_notes_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultation_notes', to='customers.customer')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_notes_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-consultation_date'],
            },
        ),
    ]
