# Generated by Django 5.1.6 on 2026-06-12 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultationnote',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
