# Generated by Django 5.1.6 on 2026-06-12 14:56

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=150)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other'), ('not_specified', 'Not Specified')], default='not_specified', max_length=20)),
                ('mobile_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('time_of_birth', models.TimeField(blank=True, null=True)),
                ('place_of_birth', models.CharField(blank=True, max_length=150)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('timezone', models.CharField(blank=True, max_length=50)),
                ('occupation', models.CharField(blank=True, max_length=100)),
                ('education', models.CharField(blank=True, max_length=100)),
                ('marital_status', models.CharField(choices=[('single', 'Single'), ('married', 'Married'), ('divorced', 'Divorced'), ('widowed', 'Widowed'), ('not_specified', 'Not Specified')], default='not_specified', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['customer_name'],
            },
        ),
        migrations.CreateModel(
            name='APIData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_source', models.CharField(choices=[('manual', 'Manual'), ('api', 'API'), ('imported_excel', 'Imported Excel'), ('imported_csv', 'Imported CSV'), ('imported_software', 'Imported Software')], default='manual', max_length=30)),
                ('api_provider', models.CharField(blank=True, max_length=100)),
                ('api_name', models.CharField(blank=True, max_length=100)),
                ('api_type', models.CharField(choices=[('birth_chart', 'Birth Chart'), ('dasha', 'Dasha'), ('transit', 'Transit'), ('kp', 'KP'), ('ashtakavarga', 'Ashtakavarga'), ('compatibility', 'Compatibility'), ('divisional_charts', 'Divisional Charts'), ('other', 'Other')], default='birth_chart', max_length=30)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('request_parameters', models.JSONField(blank=True, default=dict)),
                ('lagna', models.CharField(blank=True, max_length=100)),
                ('moon_sign', models.CharField(blank=True, max_length=100)),
                ('sun_sign', models.CharField(blank=True, max_length=100)),
                ('nakshatra', models.CharField(blank=True, max_length=100)),
                ('pada', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('current_mahadasha', models.CharField(blank=True, max_length=100)),
                ('current_antardasha', models.CharField(blank=True, max_length=100)),
                ('raw_api_response', models.JSONField(blank=True, default=dict)),
                ('parsed_response', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_data_records', to='customers.customer')),
            ],
            options={
                'ordering': ['-request_date'],
            },
        ),
    ]
